// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvYikUwETtmPy707IK6ebaXex8xhYuqQ',
    appId: '1:69512579449:web:f3c9ffc0eaaaeff4e987a8',
    messagingSenderId: '69512579449',
    projectId: 'vishare-project',
    authDomain: 'vishare-project.firebaseapp.com',
    storageBucket: 'vishare-project.firebasestorage.app',
    measurementId: 'G-H63BSCMC89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4qt1uS9aimM2f-tIbMyWKqi7jEu67mWY',
    appId: '1:69512579449:android:38ba71fd6b4f291ae987a8',
    messagingSenderId: '69512579449',
    projectId: 'vishare-project',
    storageBucket: 'vishare-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdu82OlRdvXKdC8DyYW0FZUh96emP1PTs',
    appId: '1:69512579449:ios:a7af34dab979dbb9e987a8',
    messagingSenderId: '69512579449',
    projectId: 'vishare-project',
    storageBucket: 'vishare-project.firebasestorage.app',
    iosBundleId: 'com.example.vishare',
  );
}
